# Generated by Django 5.1.7 on 2025-04-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sub_Category',
            new_name='SubCategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub',
            new_name='sub_category_name',
        ),
    ]
