# Generated by Django 5.1.7 on 2025-04-20 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_manufacturer_productcolor_productsize_site_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SubCategory',
            new_name='subcategory',
        ),
    ]
