# Generated by Django 5.1.7 on 2025-04-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_cartitem_user_remove_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='hex_code',
            field=models.CharField(blank=True, default='#000000', help_text='Hex color code like #000000', max_length=7),
        ),
    ]
