# Generated by Django 5.1.7 on 2025-04-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_address_address_type_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_activte',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
