# Generated by Django 5.1.7 on 2025-04-28 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_address_address_line_address_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_activte',
            new_name='is_activate',
        ),
    ]
