# Generated by Django 5.1.7 on 2025-04-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_is_activte_product_is_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
