# Generated by Django 5.1.7 on 2025-06-03 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_review_delete_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='vector_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
